### PR TITLE
Feature/hover participants

### PR DESCRIPTION
**Pull request by MidnightJava**
Re-submitting PR (#159) previously submitted to branch development. This change provides a re-factored Hover capability. See commit comments and Brainwy Tracker item #653 (https://sw-brainwy.rhcloud.com/tracker/PyDev/653)  for details.

### CODE REVIEW

**Comment by fabioz** [comment]
After resolving the conflicts and applying the changes, I no longer have hover info for the markers (i.e.: when there's some issue in the code, hovering over the issue doesn't show the problem).

You can get the "new_hover" branch I submitted to get the resolved conflicts / minor changes I did.

**Comment by MidnightJava** [comment]
Hi Fabio,

I pulled the new branch and I can't duplicate the problem you're seeing.
Could you please confirm that in Preferences PyDev->Editor->Hover you have
"PyDev Marker Hover" checked and either

"Combine Hovers" selected with "Preempt" not checked for any higher
priority (lower number) hover besides PyDev Marker Hover

or

"Use highest priority Hover" selected and no higher priority (lower number)
hovers checked besides PyDev Marker Hover.

It would be helpful to try it both ways, to see if the problem occurs when
using the Marker Hover as the highest priority hover and also when
combining the Marker Hover with other hovers. I see the hover text when
using any valid combination of settings.

Please let me know either way. If you still see the problem, I'll continue
to investigate and try to find a way to duplicate what you're seeing.

To make sure we're on the same page: when I have an error in the code (say
an undefined variable) the variable is underlined in red, and I see the
error msg when I hover over the variable. I think this hover info is what
you're not seeing? I uncheck PyDev Marker Hover in the preferences and I no
longer see the hover, so it is the Marker hover contributing it.

-Mark

**Comment by fabioz** [comment]
My settings are as follows:

http://imgur.com/y5cZqt0

The file is:

```
def check2(aa):
    undefined_variable
```

And when hovering over the undefined_variable, nothing happens -- in the debugger, I can see that 

org.python.pydev.editor.hover.PyEditorTextHoverProxy.getHoverRegion(ITextViewer, int)

is called having as the hover an org.python.pydev.editor.hover.PyEditorTextHoverProxy which has a org.python.pydev.editor.hover.PyDocstringTextHover as its fHover (so, I only have results for the docstring hover)...

Haven't researched further why this actually happens.

**Comment by MidnightJava** [comment]
I'm using the same settings, still not able to duplicate. One more idea I
have is to see if you;re also contributing to the old hover extension
point. If so, that will disable the new extension point. For backward
compatibility I made it so developers have to explicitly remove old hover
contributions to get the new behavior. If that's the problem, then you
should have been getting no combined hovers at all. Also I think the pref
page would be disabled in this case, with a message saying that an old
style hover contribution was detected. So it seems unlikely this is the
problem, but worth mentioning just in case.

-Mark

**Comment by MidnightJava** [comment]
Until I can find a way to reproduce the problem, I think the best I can
do is describe what I see in my debugger and maybe you can see where it's
getting a different result in yours.

In PyEditConfiguration#getTextHover() at line 103, the first hoverDescs
item encountered (assuming you still have "Combine Hovers" radio button
selected) should be the descriptor that creates an instance of
DefaultPyDevCombiningHover. In the PyEdityorTextHoverProxy created with
this descriptor, in createHover() fHover should be set to an instance of
DefaultPyDevCombiningHover. In that class, all the registered text hovers
should be added to the List fInstantiatedTextHovers in method
checkTextHovers(), based on the descriptors having been installed first in
installTextHovers(). PyMarkerTextHover should be one of these. Then in
getHoverInfo(), we should cycle through each of those hovers in the
 fInstantiatedTextHoverslist, and collect the hover info to concatenate
into a  response. It should go through all the hovers unless it encounters
one for which preempt is set to true (in which case it stops as soon as it
comes to a hover where the priority is lower than the one for which preempt
was true).

One other thing to check is whether you have anything contributed to
extension point pydev_combiningHover. I presume you don't have anything
contributed there, as that's just a hoof for contributing a custom
combining hover implementation. If you contribute to that extension point,
the class provided will be used in place of DefaultPydevCombiningHover, and
its implementation will determine whether PyMarkerTextHover's hover info is
included.

Hope that helps. I'll continue to try to think of something to try to
duplicate the problem on my end.

-Mark

On Thu, Mar 17, 2016 at 1:43 PM, Mark Leone <mark.leone@axiosengineering.com

**Comment by MidnightJava** [comment]
Fabio, are you still not seeing the marker hovers?

**Comment by fabioz** [comment]
I still didn't have time for debugging it, but it's the next item in my
todo list (although I 'm on a big holiday here in Brasil and I will only
take a look at this next week).

**Comment by MidnightJava** [comment]
No worries. I'm not in any hurry, just wanted to make sure I didn't miss
something and the ball was in my court. Enjoy your holiday. Sorry I made
you think about debugging. Erase the memory. :)

-Mark

**Comment by fabioz** [comment]
Sorry for the delay... now, I was finally able to debug it here and saw the issue:

When a new workspace is created, the code enables the docstringt text hover and the marker text hover through:

        checkHoverEnabled(PyDocstringTextHover.ID);
        checkHoverEnabled(PyMarkerTextHover.ID);

But any other hover contributed is by default disabled, which includes the combining hover (so, if you create a new workspace you should see the issue happen). This shouldn't really be so... ideally the contribution should say whether it should start enabled or disabled (the debug hover should also be enabled by default) -- strangely, even being disabled by default (i.e.: without having anything in the preferences, when the preferences page was opened, it appeared enabled).

I must say that I found the code which manages the preferences a bit tricky to deal with... one observations in this area:

Instead of having a preference for each attribute, I think it could have a single preference for each entry (that way code as the org.python.pydev.editor.hover.PyEditorTextHoverDescriptor.initializeFromPreferences(PyEditorTextHoverDescriptor[], boolean) wouldn't need to load multiple keys and do many initialization blocks -- and saving should also be simpler -- this means that the preference key would be something as "HOVER_DESCRIPTOR_pyMarkerTextHover" -- this would make it easier to initialize the value as you can just use IPreferenceStore.setDefault for each hover and then when the user changes something it'll just use IPreferenceStore.setValue (and restoring is a matter of using IPreferenceStore.setToDefault).

Other things to check:

1. org.python.pydev.plugin.PydevPlugin.getPyEditorTextHoverDescriptors(boolean) should not have an argument: it caches things internally without caring about that, so, there may be issues related to wrong values later on -- the flag seems to be used just to get the default value for restoring, but if the preference is changed as I said above, this shouldn't be a problem anymore.

2. I think it's a bit strange that the combining hover is PyEditorTextHoverDescriptor[0]: I think we don't need to let users override that (i.e.: just use in the preferences a boolean setting and if true create the combining hover and just return it wrapping the other ones, otherwise, return the other ones without it -- I think that would also make the code easier to follow as right now it's a bit strange that places such as PyEditorHoverConfigurationBlock access fHoverConfigs[0] expecting to find the default there...).

**Comment by MidnightJava** [comment]
Thanks, Fabio. I'll get back into this hopefully next week sometime.

**Comment by MidnightJava** [comment]
FYI I had a deadline at work last week that prevented me working on this. I expect to get to it later this week.

**Comment by fabioz** [comment]
No problems ;)

**Comment by MidnightJava** [comment]
I'm working on the code and I noticed that override annotations on methods for subclasses and interface implementations were removed during the merge. Is that intentional or an oversight?

**Comment by MidnightJava** [comment]
After re-familiarizing myself with the code, I understand your comments in detail. I'm fine with all your suggestions, but want to make sure you're aware of one implication.

The current design with preference keys associated with each pref value was copied from the JDT implementation. I agree it's convoluted and would be better the way you suggested, and am happy to do that. Just want to make sure you understand it will diverge from the JDT implementation. One of the design goals identified early on was to copy JDT as much as practicable. Of course that's not an absolute concern, and the implementation diverges in other areas already as needed. Just thought I'd point out that this is the JDT design and confirm you want to diverge.

**Comment by fabioz** [comment]
Related to the override annotations, I didn't notice it (they should be kept).

Personally, I think it's fine to diverge from JDT (we gained from using it as a starting point, but I don't think we really gain anything by keeping some code around just to be similar to it after the copy).

**Comment by MidnightJava** [comment]
Yes, I agree. Especially as I realized that I added a few preferences,
which makes the original design even more cumbersome.

Rather than add a preference key for each hover item and packing and
unpacking all the attribute values in that preference, I'm going to create
a separate key for each hover-attribute combination. That is, there will be
keys PYDEVHOVER_HOVER-1_PRIORITY, PYDEVHOVER_HOVER-1_ENABLED, etc. And then
similar keys for hover-2, hoever-3, etc. Let me know if you'd prefer
something different.

**Comment by MidnightJava** [comment]
I've run into a bit of a problem changing the preference keys as suggested, and I think I see now why JDT did it the way they did. The OverlayPreferenceStore stores the keys for the modifier and modifierMask of each hover. It has to be created before the preference page is loaded. Therefore it's impossible to create it with keys that include the IDs of the contributed hovers. Rather there needs to be just keys that identify modifier and modiferMask values for all hovers, and when the preference page is loaded it puts values for all contributed hovers into those keys. I tried finding a way to set the OverlayPreferenceStore keys after the preference page is created, but I haven't been successful. There is quite a confusing interplay between the various classes in the class hierarchies for the preference page and the preference block it uses, so maybe I'm missing some way to do it. But I think I'm ready to give up on the attempt.

What I'd like to do is keep the modifications I already did for the preference keys for the other attributes (enable, preempt, priority), with a pref key for each hover-attribute combination. And then just use the OverlayKeyStore with a single pref key for all modifiers and all modifierMasks as described above. The modifier and modiferMask prefs are set in a different place than the other prefs are set, so I don't think that will be confusing to handle them separately. And I can comment the code explaining why the modifier and modiferMask keys are handled the way they are.

Let me know if you have any objection to this. I have most of the other changes coded. I just need to re-factor the combining  hover.

**Comment by MidnightJava** [comment]
So I found a way to initialize the overlay store working with hover-specific preferences. The implementation is a bit odd in the following sense. As before, PyEditorTextHoverDescriptor gets the contributed hovers from extension point contributions, whenever PyDevPlugin has not cached them yet or the cache has been cleared for a reset. PyEditorTextHoverDescriptor sets default prefs from the extension point definition, and then initializes the hovers from preferences. But it does the latter in two steps:

1. It initializes the modifier and modiferMask attributes from the OverlayPrefernecStore, which it references statically from the Pref page configuration block.
2. It initializes the other attributes from the regular preference store.

I'm not sure why we have the OverlayPreferenceStore for the modifier and modiferMask settings. That class creates a local preference store which essentially copies certain pref values from the parent to the local store, and updates them when changes are made to the parent store. Then when the pref page closes, it copies the values back from the local store to the parent store.

I don't understand why the JDT implementation did this. It seems we could just use the normal prefs for all attributes. But I'm concerned that I'm missing some implication, and there would be side effects if I get rid of the OverlayPreferenceStore.

I'll leave it the way I have it, unless someone can tell me they know what the intent of the OverlPrferenceStore is and it doesn't apply in the PyDev implementation.

At any rate, I now have separate keys per hover for each attribute, including the modifier and modifierMask.

**Comment by fabioz** [comment]
I think it's something due to historical issues (historically the preferences had performance issues, but I don't think the current implementation has those issues). 

So, right now, i don't think there's any issue in dropping the use of the OverlayPreferenceStore.

**Comment by MidnightJava** [comment]
I completed the changes, implementing all your comments. I pushed to new_hover feature on my repo and created another pull request to your new_hover branch. Merging onto my feature/hoverParticpants branch created a ton of merge conflicts, so I thought this would be easier. If you want to me to do it some other way, just let me know.

**Comment by MidnightJava** [comment]
FYI, I just added a commit, hiding the modifier column when combining hover is selected. When in combining hover mode, the state mask was used to activate the combining hover per its modifierMask setting. So the modifierMasks for the contributed hovers are ignored. I added show/hide behavior for the modifier column to make this apparent to the user. Also now when a priority value is being set, the user sees help info added to the table label explaining that lowest number is highest priority.

The tip of the branch is now 4fd3484.

**Comment by MidnightJava** [comment]
Sorry, one more commit (78c5415). I realized I wasn't invalidating the cached hovers in the combining hovers after a preference change. So when a  hover priority was changed, for example, it wasn't reflected in combining hover mode unless the document was reloaded.

**Comment by fabioz** [comment]
Thanks, I'll review this today... as a note, I'm closing this one in favor of https://github.com/fabioz/Pydev/pull/178 as it seems that one is the one with the proper changes ;)

**Pull request closed without merging**
