### PR TITLE
Update for ticket 872. Adding Google style docstring functionality.

### PR DESCRIPTION
**Pull request by ghbcode**

### CODE REVIEW

**Comment by fabioz** [comment]
I started reviewing this (sorry for the delay), but it seems the implementation is not doing what I expected.

i.e.:

There are 2 actions related to docstrings: creating the docstring and updating the docstring. Those are activated by going to the line of a function (say `def my_method(a, b):`) and doing `Ctrl+1`, `Make Docstring` (if one doesn't exist) or `Update Docstring` (to only add new parameters if a docstring already exists).

So, `Make Docstring` for `def my_method(a, b):` when selecting google style should create something as:

```
    '''
    Args:
        a:
        b:
    '''
```
but it's creating something as:

```
    '''
    
    param a:
    param b:
    '''
```

and if that method is later changed to `def my_method(a, b, c):`, `Ctrl+1`, `update docstring` should update it to something as:

```
    '''
    Args:
        a:
        b:
        c:
    '''
```

So, this pull request still needs additional work to be integrated. For testing the creation of docstrings, you should do what `org.python.pydev.editor.correctionassist.AssistDocStringTest.check(String, String, int)` is doing, but passing the google style.

I also think that the `DOCSTRINGSTYLE_GOOGLE` should actually store a `"G"` char to be checked when applying the docstring (the code which creates/updates the docstring should check if that's the docstring style being used and act accordingly).

Also, even after automated tests are done, it's interesting to manually test it to make sure it's working as intended ;)

**Comment by ghbcode** [comment]
Fabio,

I think that it is better for me to carry on regarding ticket 872 within
this thread. I *finally* had some time to work on this and I have what I
think is a working version and now need to write tests. Please note that I
noticed the following behavior with the docstring functionality. My
solution for now will work like what you see below.

   - on HEAD for both Sphinx and EpiDoc dosctring settings
      - adding docstring works as expected
      - updating the docstring where you have x parameters and you x +1,
      x + 2, .... x+n works as expected
      - if the current docstring is one style, say EpyDoc, and you update
      the docstring with style Sphinx, whether you add more parameters or not,
      you will get an append of the parameters as you see below. In the case
      below the first docstring as EpyDoc with two parameters and I updated the
      preference to Sphinx and added a third parameter. I simply would like to
      point this out.
      -
      def funcSphinx(a, b, c):
          '''

          @param a:
          @param b:

          :param a:
          :param b:
          :param c:
          '''
      - if you try to update the docstring by reducing the number of
      parameters, it does not seem to work. You get the same docstring
pre update.
      -
      def func2(a, b):
          '''

          :param a:
          :param b:
          :param c:
          '''
          print(sys.api_version)

Anyway, those are only my observations and I will proceed with the Google
style docstring tests.

Thanks!

**Comment by fabioz** [comment]
I that the behavior where it gets confused when the style changes is Ok (i.e.: the user is expected to use a single style throughout a project).

Regarding the update not removing params, I think that's Ok (that'd be a separate feature, but it may be tricky to know up to where to delete, so, I think the current behavior is reasonable).

**Comment by ghbcode** [comment]
Fabio,

I just created pull request 237. This covers ticket 872 and I hope that it
is to your liking. There is a conflict that needs attention though I think
it will be easy to revolve. Please let me know if you need anything further
from me.

Thanks!

**Pull request closed without merging**
