### PR TITLE
[Feature] Context menu for test selection tree.

### PR DESCRIPTION
**Pull request by rgom**
Provide context menu from test selection tree to allow instant
configuration (without running them first).

### CODE REVIEW

**Comment by rgom** [comment]
This pull request is related to https://www.brainwy.com/tracker/PyDev/829
It's based on another branch to provide test names in launch configurations.
I'll clean that up after I get a green light to proceed.

**Comment by rgom** [comment]
This pull request is related to https://www.brainwy.com/tracker/PyDev/829
It's based on another branch to provide test names in launch configurations.
I'll clean that up after I get a green light to proceed.

**Comment by fabioz** [comment]
Hi, just merged that one... conflict is because I did a git stash in the process and it lost history (sorry about that) -- please update this one based on the current master branch to proceed.

As a note, I think it shouldn't be a context menu but rather a link to "Customize test run" (as most users will not even be aware that it exists through a context menu).

**Comment by rgom** [comment]
Thank you.
The history wasn't important at all, but it takes some time to rebase more than one commit, especially when changing and altering the same code.
I have just pushed my branch after rebasing.
I have tested it briefly, but I'm not sure if I didn't miss anything from your recent changes - I'll try to look at that later.
Initial testing looks promising - nothing broke.

As for the merit. The thing is the menu is context specific. And for that context menu seemed the best.
For instance if there's a tree of TestClass with test1 and test2, clicking on those nodes should provide links to different launch configurations. That was the idea. Or did I misread your comment?

What would be the next steps?

Regards,
Robert

**Comment by fabioz** [comment]
Humm, I thought the idea was that the run configuration would be available to what's filtered in the run (as the idea is that if the user wants to run a single test he should Ctrl+Shift+Up/Down to pre-select what he wants to run or can pre-filter what he wants).

I think I'd rather have it work that way than on a context menu... (not that both couldn't be available, but I think this will be a pretty hidden feature if only available through the context menu).

**Comment by rgom** [comment]
Thank you for the feedback.
Let me elaborate.

The story started with the following goal (user story) in mind:
  - as an user I'd like to conveniently customize specific test launch configuration, even without running it first

The test selection tree seemed to me as the best choice, as it's mostly used by us. Context menu is not occupied by any other actions. And the action (customize) is more general (common) than what we'd like to do (set env vars or similar).
I could easily extend that to change window title from "PyDev: Select tests to run" to "PyDev: Select tests to run (right click to customize)". That could alleviate the issue of the feature being hidden.

To be honest, I don't follow the other solution. There are two elements to consider: text and tree. Even if I provide a link (similar to "Configure test runner") at the bottom, what would be the use case?

  - Enter exact test names in the text field? But that's additional work (manual typing), and I couldn't even make it work for multiple tests.

  - Or consider only those tests selected in the tree? That would make more sense and could result in more or less the same as the context menu. Something like:
    - launch test selection (ctrl-f9)
    - filter test case names if necessary in text area
    - select individual tests in the tree (single or multiple, as needed)
    - click on newly provided "Customize launch" link below the tree

I'm naturally biased toward initial design and really would like it to be merged for actual work here, but can't proceed without your approval, so I'd wait for your opinion.

Regards,
Robert

**Comment by fabioz** [comment]
On my suggestion, it'd create a launch configuration for all visible tests and edit it (the user would pre-filter to select the tests he wants).

Still, I think we can proceed with your initial suggestion... I think it will be less visible to the users, but thinking about a bit more, I don't think that this is a really critical feature for most use cases, so, leaving it more hidden is probably ok -- if someone asks for it, it'll still be available (and the different behavior may still be added later on).

**Comment by rgom** [comment]
Thank you for the recent feedback.
So ... is there anything else I can do in order to get this PR merged?

Regards,
Robert

**Comment by fabioz** [comment]
Oh, sorry, I was under the impression that you still needed to do some work before I review it... I'll review later this week then.

**Comment by fabioz** [comment]
Thanks for the pull request. I've just merged it ;)

As a note, I did some changes when reviewing/testing the code. You may see them at:

https://github.com/fabioz/Pydev/commit/f459870dee3517e011803311ee6db47bad6f441c

**Comment by rgom** [comment]
Wow,
thanks a lot. Waiting anxiously for the release.

As a side note - initially I didn't close the window, as for some reason it
resulted in duplicate run.
I wanted to verify it now, but I have a mismatch in officially installed
Pydev (5.9) and newly required (6.0), which causes whole launching to fail.
Will probably wait for the release (or is there a way to customize things
to allow them to run?)

Eventually I'll wait for the release.

Regards,
Robert

**Comment by fabioz** [comment]
Just made an additional fix: https://github.com/fabioz/Pydev/commit/c47f64421519124631abb7c13b4fcf679ec046b7

I'll make a release soon (hopefully today, otherwise on friday).

You should be able to just launch PyDev with a different version by disabling any conflicting features (you can disable other related features by configuring the launch configuration for a new `Eclipse Application`).

**Comment by rgom** [comment]
I've just verified that fix successfully.

Thank you!

Robert

**Pull request merged**
