### PR TITLE
Add "Allow tab stop in comments" option

### PR DESCRIPTION
**Pull request by jheiv**
Pull request adds preference option (In PyDev->Editor->Tabs) to allow tab stops to function in tabs (instead of exactly 4 spaces, regardless of the column).

See [this StackOverflow question](http://stackoverflow.com/questions/29639276/pydev-tab-alignment-in-inline-comments/29672423#29672423) for a more thorough explanation.

This logic in `PyAutoIndentStrategy:customizeDocumentCommand` was adjusted a bit, so if the command is:

* In a comment context,
* Is a tab character,
* The `tabStopInComments` preference is set,

the short circuit return that is there is skipped, and the tab is handled as a tab in the default context.

This preference is disabled by default.

I also added a test in `PyAutoIndentStrategyTest:testAllowTabStopInComments` that enables the preference in the test preferences, and runs some tests, verifying that the command is customized as expected. (between 1-4 spaces, inclusive, depending on the current column).

**Note:** I only ran the PyAutoIndentStrategyTest TestCase, I couldn't figure out how to run a more comprehensive test suite, but I don't expect my changes have a huge impact outside of the tests in that TestCase.

**Note2:** My IDE is set up to strip trailing whitespace automatically, I apologize for the unnecessary changes.

### CODE REVIEW

**Comment by jheiv** [comment]
I think the current test is sufficient, but just in case, I expanded it to re-disable the option, and ensure we (again) get exactly 4 spaces.  If you want, I can create a new PR, but if you're interested, the [change is here](https://github.com/jheiv/Pydev/commit/ec168db12f415fd4a4673efdbf53ba21da083bf5).

**Comment by fabioz** [comment]
Note: just wanted to add that I'll definitely integrate this before the next release (things are a bit busy on my side right now, so, I still haven't got time to integrate it).

**Comment by jheiv** [comment]
No worries, and sounds good.  Just happy to help in a tiny way a tool that helps me on a much larger scale regularly.  Thanks again for PyDev.

**Comment by fabioz** [comment]
Just merged. Thank you for the patch... as a note, I also changed it to make it True by default -- as I think that's really more standard :)

**Pull request merged**
