### PR TITLE
bug in remote debugging resolved

### PR DESCRIPTION
**Pull request by Tusharsb**
I was getting 'too many values to unpack' error on the 'for loop' line here. the bug got resolved once i changed these lines

### CODE REVIEW

**Comment by Tusharsb** [comment]
Maybe the change is not good for locale debugging. But this change makes remote debugging work!

I was doing remote debugging on a remote machine. I did filled PATHS_FROM_ECLIPSE_TO_PYTHON too. The plugin works fine when debugging on local machine. But wasnt working on remote locations until I made this change.

I had to setup remote debugging in 2 separate situations in past 2 weeks. And in both situations my remote debugging worked only after this change.

**Comment by fabioz** [comment]
How did you fill PATHS_FROM_ECLIPSE_TO_PYTHON?

**Comment by Tusharsb** [comment]
PATHS_FROM_ECLIPSE_TO_PYTHON = [r'/home/vagrant/src',r'/home/sb/experiments/vagrant_getting_started/src']

**Comment by fabioz** [comment]
So, that's the issue you have... you created a list with 2 strings instead of a list with a tuple with 2 strings... (i.e.: it should be [(r'/home/vagrant/src',r'/home/sb/experiments/vagrant_getting_started/src')] -- you change makes it work only with a single path, whereas multiple path translations could be specified).

**Comment by Tusharsb** [comment]
oops. Thanks for pointing out my bug. I will restore my build to your code now

**Pull request closed without merging**
